// <auto-generated />
using ChartServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChartServer.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20240528221457_Add tables")]
    partial class Addtables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("ChartServer.Data.Entities.StatRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Middle")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("tblRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
